import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./(components)/BootstrapClient";
import Navbar from "./(components)/Navbar";
import Footer from "./(components)/Footer";
import { UserTokenProvider } from "./(Context)/UserToken";
import { APIsContextProvider } from "./(Context)/APIsContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "e-commerce Nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserTokenProvider>
          <APIsContextProvider>
            <Navbar />
            {children}

            <Footer />
          </APIsContextProvider>
        </UserTokenProvider>

        <BootstrapClient />
      </body>
    </html>
  );
}
